# Generated by Django 4.2.6 on 2023-10-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='id',
        ),
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.CharField(default='example@123', max_length=255),
        ),
        migrations.AddField(
            model_name='instructor',
            name='instructor_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='instructor',
            name='name',
            field=models.CharField(default='John Doe', max_length=255),
        ),
        migrations.AddField(
            model_name='instructor',
            name='performance_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instructor',
            name='phone_number',
            field=models.CharField(default='9389040033', max_length=12),
        ),
        migrations.AddField(
            model_name='instructor',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instructor',
            name='type',
            field=models.CharField(default='Permanent', max_length=255),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='department',
            field=models.CharField(default='CSE', max_length=255),
        ),
    ]
