# Generated by Django 4.2.6 on 2023-10-22 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('course_department', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(default='John Doe', max_length=255)),
                ('department', models.CharField(default='CSE', max_length=255)),
                ('type', models.CharField(default='Permanent', max_length=255)),
                ('salary', models.IntegerField(default=0)),
                ('email', models.CharField(default='example@123', max_length=255)),
                ('phone_number', models.CharField(default='9389040033', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Research_by_faculty',
            fields=[
                ('research_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('research_area', models.CharField(max_length=100)),
                ('status', models.CharField(default='active', max_length=100)),
                ('budget', models.CharField(default='', max_length=100)),
                ('research_topic', models.CharField(max_length=100)),
                ('research_department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_year', models.IntegerField(max_length=255)),
                ('semester', models.IntegerField(max_length=255)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.courses')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instructor')),
                ('research_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.research_by_faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('publication_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('publication_date', models.DateField()),
                ('publication_type', models.CharField(max_length=100)),
                ('publication_link', models.CharField(default='', max_length=100000)),
                ('research_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.research_by_faculty')),
            ],
        ),
    ]
